from tkinter import *

def Calculator_app():
  window = Tk()
  l = Label(window,text = "",font = ("Calibri",30),anchor = "ne",width = 18)
  l.grid(column = 0,row=0,columnspan = 4,pady = 10)
  b1 = Button(window,text = "7",width = 10,command = lambda:add("7", l))
  b1.grid(row=1,column = 0)
  b2 = Button(window,text = "8",width = 10,command = lambda:add("8", l))
  b2.grid(row=1,column = 1)
  b3 = Button(window,text = "9",width = 10,command = lambda:add("9", l))
  b3.grid(row=1,column = 2)
  b4 = Button(window,text = "*",width = 10,command = lambda: add("*", l))
  b4.grid(row=1,column = 3)
  b5 = Button(window,text = "4",width = 10,command = lambda:add("4", l))
  b5.grid(row=2,column = 0)
  b6 = Button(window,text = "5",width = 10,command = lambda:add("5", l))
  b6.grid(row=2,column = 1)
  b7 = Button(window,text = "6",width = 10,command = lambda:add("6", l))
  b7.grid(row=2,column = 2)
  b8 = Button(window,text = "+",width = 10,command = lambda:add("+", l))
  b8.grid(row=2,column = 3)
  b9 = Button(window,text = "1",width = 10,command = lambda:add("1", l))
  b9.grid(row=3,column = 0)
  b10 = Button(window,text = "2",width = 10,command = lambda:add("2", l))
  b10.grid(row=3,column = 1)
  b11 = Button(window,text = "3",width = 10,command = lambda:add("3", l))
  b11.grid(row=3,column = 2)
  b12 = Button(window,text = "-",width = 10,command = lambda:add("-", l))
  b12.grid(row=3,column = 3)
  b13 = Button(window,text = "AC",width = 10,command = lambda: clear(l))
  b13.grid(row=4,column = 0)
  b14 = Button(window,text = "0",width = 10,command = lambda:add("0", l))
  b14.grid(row=4,column = 1)
  b15 = Button(window,text = "=",width = 10,command = lambda: result(l))
  b15.grid(row=4,column = 2)
  b16 = Button(window,text = "/",width = 10,command = lambda:add("/", l))
  b16.grid(row=4,column = 3)
  window.geometry("600x900")
  window.title("Calculator")
  window.configure(bg = "black")
  window.mainloop()

def add(n, l):
  t = l.cget('text') + n
  l.configure(text = t)
def clear(l):
  l.configure(text="")
def result(l):
  answer = eval(l.cget("text"))
  l.configure(text=str(answer))